checks:
    php:
        code_rating: true
        duplication: true
build:
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=phpunit-coverage'
        coverage:
          file: 'phpunit-coverage'
          format: 'php-clover'
