name: "Mutation Tests"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  mutation-tests:
    name: "Mutation Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "locked"
      - name: "Mutation Tests"
        run: "composer test:mutants"
