name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    continue-on-error: ${{ matrix.experimental }}
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php:
          - "7.4"
          - "7.3"
          - "7.2"
          - "7.1"
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false
        include:
          - php: "8.0"
            dependencies: "highest"
            composer-options: "--ignore-platform-reqs"
            experimental: true

    steps:
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
      - uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "${{ matrix.composer-options }}"
      - run: composer build
